<?php

namespace App\Admin\Actions\Grid;

use Dcat\Admin\Actions\Response;
use Dcat\Admin\Grid\GridAction;
use Dcat\Admin\Grid\RowAction;
use Dcat\Admin\Traits\HasPermissions;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class ShowCustonerTransaction extends GridAction
{
    /**
     * @return string
     */
	protected $title = 'Title';

    protected function script()
    {
//        parent::script(); // TODO: Change the autogenerated stub

        $path = admin_url('point/'. $this->getKey());


        return <<<JS
            $('.grid-check-row').on('click', function () {
                layer.open({
                  type: 2
                  ,content: '$path'
                });
            });
            JS;
    }

    protected function html()
    {

        // 获取当前行数据ID
        $id = $this->getKey();

        // 获取当前行数据的用户名
        $username = $this->row->username;

        // 这里需要添加一个class, 和上面script方法对应
        $this->setHtmlAttribute(['data-id' => $id, 'email' => $username, 'class' => 'grid-check-row']);

        return parent::html(); // TODO: Change the autogenerated stub


    }
}
